load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_test(
    name = "BazelPythonPrimitivesTest",
    srcs = ["BazelPythonPrimitivesTest.sh"],
    data = [
        "//examples:testdata",
        "//src/bin:kepler-formal",
    ],
)

cc_test(
    name = "MiterTests",
    srcs = ["MiterTests.cpp"],
    data = [
        "//src/bin:kepler-formal",
        "//examples:testdata",
    ] + glob(["*.yaml"]),
    env = {
        "KEPLER_BIN": "$(rootpath //src/bin:kepler-formal)",
        "TEST_DATA_PREFIX": "",
    },
    deps = [
        "//src/clauses:kepler_clauses",
        "//src/config:kepler_config",
        "//src/formal:formal_structures",
        "//src/strategies:formal_strategies",
        "@naja//src/core:naja_core",
        "@naja//src/nl/netlist:naja_nl",
        "@naja//src/nl/netlist:naja_snl_visual",
        "@naja//src/dnl:naja_dnl",
        "@naja//src/optimization:naja_opt",
        "@naja//src/nl/formats/liberty:naja_snl_liberty",
        "@naja//src/nl/formats/verilog:naja_snl_verilog",
        "@naja//src/nl/netlist/serialization/capnp:naja_nl_dump",
        "@googletest//:gtest",
    ],
)
