load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel:naja_includes.bzl", "NAJA_HEADER_COPTS")

sh_test(
    name = "BazelPythonPrimitivesTest",
    srcs = ["BazelPythonPrimitivesTest.sh"],
    data = [
        "//example:testdata",
        "//src/bin:kepler-formal",
    ],
)

cc_test(
    name = "MiterTests",
    srcs = ["MiterTests.cpp"],
    data = [
        "//src/bin:kepler-formal",
        "//example:testdata",
    ] + glob(["*.yaml"]),
    env = {
        "KEPLER_BIN": "$(rootpath //src/bin:kepler-formal)",
        "TEST_DATA_PREFIX": "",
    },
    copts = NAJA_HEADER_COPTS,
    deps = [
        "//src/clauses:kepler_clauses",
        "//src/config:kepler_config",
        "//src/formal:formal_structures",
        "//src/strategies:formal_strategies",
        "@naja",
        "@naja//:naja_extra_headers",
        "@googletest//:gtest_main",
    ],
)
