# tinyrocket_sec_config.yaml
format: verilog
verification: SEC
max_k: 1000
input_paths:
  - tinyrocket.v
  - tinyrocket.v
liberty_files:
  - NangateOpenCellLibrary_typical.lib
  - fakeram45_1024x32.lib
  - fakeram45_64x32.lib
  - fakeram45_64x15.lib
log_level: info
solver: kissat
