// Copyright 2026 keplertech.io
// SPDX-License-Identifier: GPL-3.0-only

// Generated by Yosys 0.53 using synth_xilinx.
module xilinx_register_slice(clk, rst, ce, d, x, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [1:0] _06_;
  input ce;
  wire ce;
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  input rst;
  wire rst;
  input x;
  wire x;
  LUT2 #(
    .INIT(4'h6)
  ) _07_ (
    .I0(_06_[0]),
    .I1(_06_[1]),
    .O(_00_)
  );
  BUFG _08_ (
    .I(_01_),
    .O(_03_)
  );
  FDRE #(
    .INIT(1'hx)
  ) _09_ (
    .C(_03_),
    .CE(_02_),
    .D(_00_),
    .Q(_04_),
    .R(_05_)
  );
  IBUF _10_ (
    .I(ce),
    .O(_02_)
  );
  IBUF _11_ (
    .I(clk),
    .O(_01_)
  );
  IBUF _12_ (
    .I(d),
    .O(_06_[0])
  );
  OBUF _13_ (
    .I(_04_),
    .O(q)
  );
  IBUF _14_ (
    .I(rst),
    .O(_05_)
  );
  IBUF _15_ (
    .I(x),
    .O(_06_[1])
  );
endmodule
