#!/usr/bin/env bash
# Export the hermetic dependency install trees into <workspace>/deps/ so the
# plain CMake flow can build without system-installed libraries:
#
#   bazelisk run //:deps
#   cmake -B build -DCMAKE_TOOLCHAIN_FILE=$PWD/deps/toolchain.cmake
#
# Strictly opt-in: the CMake-with-system-packages flow is unaffected unless
# the toolchain file is passed. deps/ is git- and bazel-ignored and fully
# regenerated on every run (safe to delete at any time).
set -euo pipefail

if [[ -z ${BUILD_WORKSPACE_DIRECTORY:-} ]]; then
  echo >&2 "error: must be invoked via 'bazel run //:deps'"
  exit 1
fi

CAPNPROTO_PREFIX=$1
ONETBB_PREFIX=$2
BOOST_VERSION_HPP=$3 # sentinel file; boost root is two levels up
FLEXLEXER_H=$4
TOOLCHAIN_FRAGMENT=$5 # generated compiler settings, or NONE (macOS)
shift 5 # remaining: zlib outputs + headers + hermetic runtime archives

DEST="${BUILD_WORKSPACE_DIRECTORY}/deps"
STAGE="${DEST}.tmp"
# A stale stage from an interrupted run may carry read-only bits.
[ -d "${STAGE}" ] && chmod -R u+w "${STAGE}"
rm -rf "${STAGE}"
mkdir -p "${STAGE}/include" "${STAGE}/lib"

# Merge the cmake install prefixes (bin/ include/ lib/ lib/cmake/) into one
# CMake prefix. -L dereferences tree-artifact symlink chains (libtbb.so.12,
# capnpc) so deps/ survives 'bazel clean'. The CapnProto/TBB package configs
# stay valid after copying: they compute _IMPORT_PREFIX relative to their own
# location.
# Preserve mode (execute bits on bin/capnp etc.); bazel outputs are
# read-only, so restore user-write between the merges.
cp -RL --no-preserve=timestamps "${CAPNPROTO_PREFIX}"/. "${STAGE}/"
chmod -R u+w "${STAGE}"
cp -RL --no-preserve=timestamps "${ONETBB_PREFIX}"/. "${STAGE}/"
chmod -R u+w "${STAGE}"

# Header-only and single-file deps.
cp -RL --no-preserve=mode,timestamps "$(dirname "$(dirname "${BOOST_VERSION_HPP}")")/boost" "${STAGE}/include/boost"
cp -L --no-preserve=mode,timestamps "${FLEXLEXER_H}" "${STAGE}/include/"
# zlib static archive + public headers, and (on Linux) the hermetic C++
# runtime archives referenced by toolchain.cmake. libz.so is skipped —
# CMake consumers should link the static archive, and a solib copy would
# dangle.
for f in "$@"; do
  case "${f}" in
    *.a) cp -L --no-preserve=mode,timestamps "${f}" "${STAGE}/lib/" ;;
    *.h) cp -L --no-preserve=mode,timestamps "${f}" "${STAGE}/include/" ;;
  esac
done

# Hermetic compiler export: materialize the cc_toolchain's runfiles
# (clang dist, resource dir, hermetic glibc/kernel headers, CRT objects)
# under deps/llvm/<repo>/ — the layout toolchain.cmake's rewritten paths
# expect. cwd is the runfiles _main directory under 'bazel run', so the
# repo directories live one level up.
if [[ ${TOOLCHAIN_FRAGMENT} != NONE ]]; then
  mkdir -p "${STAGE}/llvm"
  for d in ../llvm+ ../llvm++*; do
    [[ -d ${d} ]] || continue
    # Keep mode (execute bits on the tools); the stage-wide chmod below
    # restores user-write.
    cp -RL --no-preserve=timestamps "${d}" "${STAGE}/llvm/$(basename "${d}")"
  done
  # The clang dist is busybox-style (clang, lld, llvm-ar, ... are all
  # symlinks to one ~200MB multi-call binary); dereferencing copies made
  # each a full copy. Re-share identical large files via hardlinks.
  canonical=""
  prev_size=""
  while IFS= read -r line; do
    size=${line%% *}
    f=${line#* }
    if [[ ${size} == "${prev_size}" ]] && cmp -s "${canonical}" "${f}"; then
      ln -f "${canonical}" "${f}"
    else
      canonical=${f}
      prev_size=${size}
    fi
  done < <(find "${STAGE}/llvm" -type f -size +10M -printf '%s %p\n' | sort -n)
fi

# Dependency resolution block; on Linux the hermetic compiler settings
# (generated from the Bazel cc_toolchain) are appended so the CMake flow
# needs no host compiler and is ABI-identical to the Bazel flow.
cat > "${STAGE}/toolchain.cmake" <<'EOF'
# Generated by 'bazel run //:deps' — do not edit.
get_filename_component(_KF_DEPS "${CMAKE_CURRENT_LIST_DIR}" ABSOLUTE)
list(APPEND CMAKE_PREFIX_PATH "${_KF_DEPS}")
set(Boost_INCLUDE_DIR "${_KF_DEPS}/include" CACHE PATH "")
set(FLEX_INCLUDE_DIR "${_KF_DEPS}/include" CACHE PATH "")
set(ZLIB_ROOT "${_KF_DEPS}" CACHE PATH "")
EOF
if [[ ${TOOLCHAIN_FRAGMENT} != NONE ]]; then
  cat "${TOOLCHAIN_FRAGMENT}" >> "${STAGE}/toolchain.cmake"
  # Compiler wrapper scripts generated alongside the fragment.
  for w in hermetic-cc hermetic-cxx; do
    cp -L --no-preserve=timestamps "$(dirname "${TOOLCHAIN_FRAGMENT}")/${w}" "${STAGE}/bin/${w}"
    chmod +x "${STAGE}/bin/${w}"
  done
fi

# Belt and braces on top of the repo .gitignore/.bazelignore entries.
printf '*\n' > "${STAGE}/.gitignore"

chmod -R u+w "${STAGE}"
rm -rf "${DEST}"
mv "${STAGE}" "${DEST}"

echo "Hermetic dependencies exported to ${DEST}"
echo "Use with: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${DEST}/toolchain.cmake"
