"""Generate CMake toolchain settings from the resolved cc_toolchain.

Used by //:deps to export the hermetic compiler for the plain CMake flow.
Emits three files:

- toolchain_fragment.cmake — appended to deps/toolchain.cmake; points
  CMAKE_{C,CXX}_COMPILER at the wrapper scripts and carries the link-time
  settings (linker flags, C++ runtime archives, ar).
- hermetic-cc / hermetic-cxx — POSIX sh wrappers exec'ing the exported
  clang with the zero-sysroot compile flags baked in. Flags live in the
  wrappers rather than CMAKE_<LANG>_FLAGS_INIT because third-party
  CMakeLists routinely stomp the flag variables (e.g. glucose's
  set(CMAKE_CXX_FLAGS "-std=c++11")), which would silently fall back to
  host headers and produce objects that cannot link against the hermetic
  glibc stubs.

Reuses rules_foreign_cc's toolchain capture (the same code that generates
the crosstool for the @naja/@capnproto/@onetbb cmake builds), so the CMake
flow compiles with the same flags as the Bazel flow. The load path is
private to rules_foreign_cc — pinned in MODULE.bazel; revisit on upgrades.
"""

load(
    "@rules_foreign_cc//foreign_cc/private:cc_toolchain_util.bzl",
    "get_flags_info",
    "get_tools_info",
)

def _rewrite(s, bin_external, root):
    """Rewrite execroot-relative external paths to <root>/<repo>/..."""
    s = s.replace(bin_external, root + "/")
    if s.startswith("external/"):
        s = root + "/" + s[len("external/"):]
    return s.replace("=external/", "=" + root + "/")

def _cmake_join(flag_list, bin_external):
    return " ".join([
        _rewrite(f, bin_external, "${_KF_LLVM}").replace('"', '\\"')
        for f in flag_list
    ])

def _keep_for_wrapper(flag):
    """Drop Bazel's style/diagnostic preferences from the exported wrapper.

    The wrapper's job is hermeticity (sysroot, headers, target), not
    imposing warning policy on third-party builds — cadical's configure,
    for one, fails its test compile when -Wall produces output. -Wno-*
    suppressions stay; warning-enabling -W* (incl. -Werror=*) go.
    """
    if flag == "-fcolor-diagnostics":
        return False
    return not flag.startswith("-W") or flag.startswith("-Wno-")

def _sh_join(flag_list, bin_external):
    # Double-quote each flag so the wrapper's $D expands; escape embedded
    # double quotes (e.g. -D__DATE__="redacted").
    return " ".join([
        '"%s"' % _rewrite(f, bin_external, "$D/llvm").replace('"', '\\"')
        for f in flag_list
        if _keep_for_wrapper(f)
    ])

_WRAPPER = """#!/bin/sh
# Generated by //bazel:toolchain_cmake.bzl — do not edit.
# Hermetic zero-sysroot {lang} compiler for the CMake flow; flags are baked
# in so projects that overwrite CMAKE_{lang_upper}_FLAGS cannot lose them
# (and so configure scripts that invoke $CC/$CXX directly, like cadical's
# and kissat's, compile AND link hermetically).
# -Qunused-arguments: compile-only flags are silently ignored at link.
# -idirafter ranks below all hermetic -isystem headers; needed only for
# the system Python3 (Debian multiarch pyconfig.h), the one deliberate
# host dependency.
D=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
link=1
for a in "$@"; do
  case "$a" in
    -c|-S|-E|-M|-MM|-###|--version|-dumpversion|-dumpmachine|--help|-print-*) link=0 ;;
  esac
done
if [ "$link" = 1 ]; then
  # Linking: add the toolchain's linker flags, and the C++ runtime
  # archives after the user inputs (archive order matters).
  exec "$D/llvm/{compiler}" -Qunused-arguments {flags} -idirafter /usr/include {link_flags} "$@" {post_libs}
fi
exec "$D/llvm/{compiler}" -Qunused-arguments {flags} -idirafter /usr/include "$@"
"""

def _toolchain_cmake_impl(ctx):
    tools = get_tools_info(ctx)
    flags = get_flags_info(ctx)
    bin_external = ctx.bin_dir.path + "/external/"

    cc_rel = _rewrite(tools.cc, bin_external, "")
    if cc_rel.startswith("/"):
        cc_rel = cc_rel[1:]

    # The hermetic toolchain drives C and C++ through the clang binary;
    # use the clang++ driver name for C++ (mirrors rules_foreign_cc).
    cxx_rel = _rewrite(tools.cxx, bin_external, "")
    if cxx_rel.startswith("/"):
        cxx_rel = cxx_rel[1:]
    if cxx_rel.endswith("/clang"):
        cxx_rel += "++"

    ar = _rewrite(tools.cxx_linker_static, bin_external, "${_KF_LLVM}")

    link_flags = _sh_join(flags.cxx_linker_executable, bin_external)
    cxx_runtime = " ".join([
        '"$D/lib/liblibcxx.static.a"',
        '"$D/lib/liblibcxxabi.static.a"',
        '"$D/lib/liblibunwind.static.a"',
    ])

    cc_wrapper = ctx.actions.declare_file("hermetic-cc")
    ctx.actions.write(cc_wrapper, _WRAPPER.format(
        lang = "C",
        lang_upper = "C",
        compiler = cc_rel,
        flags = _sh_join(flags.cc, bin_external),
        link_flags = link_flags,
        post_libs = "-lm",
    ), is_executable = True)

    cxx_wrapper = ctx.actions.declare_file("hermetic-cxx")
    ctx.actions.write(cxx_wrapper, _WRAPPER.format(
        lang = "C++",
        lang_upper = "CXX",
        compiler = cxx_rel,
        flags = _sh_join(flags.cxx, bin_external),
        link_flags = link_flags,
        post_libs = cxx_runtime + " -lm",
    ), is_executable = True)

    fragment = ctx.actions.declare_file("toolchain_fragment.cmake")
    ctx.actions.write(fragment, """# Hermetic compiler settings (generated from the Bazel cc_toolchain
# by //bazel:toolchain_cmake.bzl — do not edit).
set(_KF_LLVM "${{_KF_DEPS}}/llvm")
set(CMAKE_C_COMPILER "${{_KF_DEPS}}/bin/hermetic-cc")
set(CMAKE_CXX_COMPILER "${{_KF_DEPS}}/bin/hermetic-cxx")
set(CMAKE_AR "{ar}" CACHE FILEPATH "Archiver")
# llvm-ar writes the symbol index itself; ':' is CMake's no-op ranlib.
set(CMAKE_RANLIB ":")
set(CMAKE_EXE_LINKER_FLAGS_INIT "{exe_link_flags}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "{shared_link_flags}")
# The C++ runtime archives are Bazel link inputs, not driver defaults
# (see bazel/naja.BUILD.bazel); exported into deps/lib by //:deps.
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "${{_KF_DEPS}}/lib/liblibcxx.static.a ${{_KF_DEPS}}/lib/liblibcxxabi.static.a ${{_KF_DEPS}}/lib/liblibunwind.static.a -lm")
""".format(
        ar = ar,
        exe_link_flags = _cmake_join(flags.cxx_linker_executable, bin_external),
        shared_link_flags = _cmake_join(flags.cxx_linker_shared, bin_external),
    ))

    return [
        DefaultInfo(files = depset([fragment, cc_wrapper, cxx_wrapper])),
        OutputGroupInfo(fragment = depset([fragment])),
    ]

toolchain_cmake = rule(
    implementation = _toolchain_cmake_impl,
    attrs = {
        "_cc_toolchain": attr.label(
            default = Label("@bazel_tools//tools/cpp:current_cc_toolchain"),
        ),
    },
    fragments = ["cpp"],
    toolchains = ["@bazel_tools//tools/cpp:toolchain_type"],
)
