load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "xls_c2rtl_proto",
    srcs = [
        "xls/codegen/codegen_residual_data.proto",
        "xls/codegen/module_signature.proto",
        "xls/codegen/verilog_line_map.proto",
        "xls/codegen/xls_metrics.proto",
        "xls/contrib/xlscc/hls_block.proto",
        "xls/contrib/xlscc/metadata_output.proto",
        "xls/ir/channel.proto",
        "xls/ir/evaluator_result.proto",
        "xls/ir/foreign_function_data.proto",
        "xls/ir/op.proto",
        "xls/ir/ram_rewrite.proto",
        "xls/ir/transform_metrics.proto",
        "xls/ir/xls_ir_interface.proto",
        "xls/ir/xls_type.proto",
        "xls/ir/xls_value.proto",
        "xls/jit/type_layout.proto",
        "xls/netlist/netlist.proto",
        "xls/passes/optimization_pass_pipeline.proto",
        "xls/passes/pass_metrics.proto",
        "xls/passes/pass_pipeline.proto",
        "xls/scheduling/pipeline_schedule.proto",
    ],
    deps = [
        "@googleapis//google/api:field_behavior_proto",
        "@protobuf//:duration_proto",
    ],
)

cc_proto_library(
    name = "xls_c2rtl_cc_proto",
    deps = [":xls_c2rtl_proto"],
)

cc_library(
    name = "xls_c2rtl",
    srcs = [
        "xls/codegen/bdd_io_analysis.cc",
        "xls/codegen/block_conversion.cc",
        "xls/codegen/block_metrics.cc",
        "xls/codegen/block_stitching_pass.cc",
        "xls/codegen/clone_nodes_into_block_handler.cc",
        "xls/codegen/codegen_checker.cc",
        "xls/codegen/codegen_options.cc",
        "xls/codegen/codegen_pass.cc",
        "xls/codegen/codegen_pass_pipeline.cc",
        "xls/codegen/codegen_util.cc",
        "xls/codegen/codegen_wrapper_pass.cc",
        "xls/codegen/combinational_generator.cc",
        "xls/codegen/concurrent_stage_groups.cc",
        "xls/codegen/conversion_utils.cc",
        "xls/codegen/expression_flattening.cc",
        "xls/codegen/ffi_instantiation_pass.cc",
        "xls/codegen/finite_state_machine.cc",
        "xls/codegen/lint_annotate.cc",
        "xls/codegen/mark_channel_fifos_pass.cc",
        "xls/codegen/maybe_materialize_fifos_pass.cc",
        "xls/codegen/module_builder.cc",
        "xls/codegen/module_signature.cc",
        "xls/codegen/mulp_combining_pass.cc",
        "xls/codegen/name_legalization_pass.cc",
        "xls/codegen/node_expressions.cc",
        "xls/codegen/op_override_impls.cc",
        "xls/codegen/pipeline_generator.cc",
        "xls/codegen/port_legalization_pass.cc",
        "xls/codegen/priority_select_reduction_pass.cc",
        "xls/codegen/proc_block_conversion.cc",
        "xls/codegen/ram_configuration.cc",
        "xls/codegen/ram_rewrite_pass.cc",
        "xls/codegen/register_chaining_analysis.cc",
        "xls/codegen/register_combining_pass.cc",
        "xls/codegen/register_legalization_pass.cc",
        "xls/codegen/side_effect_condition_pass.cc",
        "xls/codegen/signature_generation_pass.cc",
        "xls/codegen/signature_generator.cc",
        "xls/codegen/trace_verbosity_pass.cc",
        "xls/codegen/vast/fold_vast_constants.cc",
        "xls/codegen/vast/infer_vast_types.cc",
        "xls/codegen/vast/vast.cc",
        "xls/codegen/vast/verilog_keywords.cc",
        "xls/codegen/verilog_conversion.cc",
        "xls/common/attribute_data.cc",
        "xls/common/case_converters.cc",
        "xls/common/file/filesystem.cc",
        "xls/common/file/path.cc",
        "xls/common/file/temp_file.cc",
        "xls/common/indent.cc",
        "xls/common/logging/log_lines.cc",
        "xls/common/math_util.cc",
        "xls/common/status/error_code_to_status.cc",
        "xls/common/status/ret_check.cc",
        "xls/common/status/status_builder.cc",
        "xls/common/status/status_builder_oss.cc",
        "xls/common/stopwatch.cc",
        "xls/common/strerror.cc",
        "xls/common/string_to_int.cc",
        "xls/common/symbolized_stacktrace.cc",
        "xls/common/to_string_utils.cc",
        "xls/contrib/xlscc/cc_parser.cc",
        "xls/contrib/xlscc/continuations.cc",
        "xls/contrib/xlscc/expr_clone.cc",
        "xls/contrib/xlscc/generate_fsm.cc",
        "xls/contrib/xlscc/node_manipulation.cc",
        "xls/contrib/xlscc/tracked_bvalue.cc",
        "xls/contrib/xlscc/translate_block.cc",
        "xls/contrib/xlscc/translate_io.cc",
        "xls/contrib/xlscc/translate_loops.cc",
        "xls/contrib/xlscc/translate_metadata.cc",
        "xls/contrib/xlscc/translator.cc",
        "xls/contrib/xlscc/translator_types.cc",
        "xls/data_structures/binary_decision_diagram.cc",
        "xls/data_structures/binary_search.cc",
        "xls/data_structures/inline_bitmap.cc",
        "xls/data_structures/leaf_type_tree.cc",
        "xls/data_structures/transitive_closure.cc",
        "xls/dev_tools/link_to_source.cc",
        "xls/estimators/delay_model/delay_estimator.cc",
        "xls/estimators/delay_model/delay_estimators.cc",
        "xls/estimators/delay_model/ffi_delay_estimator.cc",
        "xls/interpreter/function_interpreter.cc",
        "xls/interpreter/ir_interpreter.cc",
        "xls/ir/big_int.cc",
        "xls/ir/bit_push_buffer.cc",
        "xls/ir/bits.cc",
        "xls/ir/bits_ops.cc",
        "xls/ir/block.cc",
        "xls/ir/block_elaboration.cc",
        "xls/ir/call_graph.cc",
        "xls/ir/caret.cc",
        "xls/ir/channel.cc",
        "xls/ir/channel_ops.cc",
        "xls/ir/clone_package.cc",
        "xls/ir/code_template.cc",
        "xls/ir/dfs_visitor.cc",
        "xls/ir/elaborated_block_dfs_visitor.cc",
        "xls/ir/elaboration.cc",
        "xls/ir/events.cc",
        "xls/ir/foreign_function.cc",
        "xls/ir/format_preference.cc",
        "xls/ir/format_strings.cc",
        "xls/ir/function.cc",
        "xls/ir/function_base.cc",
        "xls/ir/function_builder.cc",
        "xls/ir/instantiation.cc",
        "xls/ir/interval.cc",
        "xls/ir/interval_ops.cc",
        "xls/ir/interval_set.cc",
        "xls/ir/ir_annotator.cc",
        "xls/ir/ir_parser.cc",
        "xls/ir/ir_scanner.cc",
        "xls/ir/keyword_args.cc",
        "xls/ir/name_uniquer.cc",
        "xls/ir/node.cc",
        "xls/ir/node_util.cc",
        "xls/ir/nodes.cc",
        "xls/ir/number_parser.cc",
        "xls/ir/op.cc",
        "xls/ir/package.cc",
        "xls/ir/partial_information.cc",
        "xls/ir/partial_ops.cc",
        "xls/ir/proc.cc",
        "xls/ir/proc_conversion.cc",
        "xls/ir/proc_elaboration.cc",
        "xls/ir/proc_instantiation.cc",
        "xls/ir/register.cc",
        "xls/ir/scheduled_builder.cc",
        "xls/ir/state_element.cc",
        "xls/ir/ternary.cc",
        "xls/ir/topo_sort.cc",
        "xls/ir/type.cc",
        "xls/ir/type_manager.cc",
        "xls/ir/value.cc",
        "xls/ir/value_builder.cc",
        "xls/ir/value_conversion_utils.cc",
        "xls/ir/value_flattening.cc",
        "xls/ir/value_utils.cc",
        "xls/ir/verifier.cc",
        "xls/ir/verify_node.cc",
        "xls/passes/array_simplification_pass.cc",
        "xls/passes/basic_simplification_pass.cc",
        "xls/passes/bdd_query_engine.cc",
        "xls/passes/constant_folding_pass.cc",
        "xls/passes/cse_pass.cc",
        "xls/passes/dataflow_simplification_pass.cc",
        "xls/passes/dce_pass.cc",
        "xls/passes/identity_removal_pass.cc",
        "xls/passes/inlining_pass.cc",
        "xls/passes/lazy_ternary_query_engine.cc",
        "xls/passes/node_dependency_analysis.cc",
        "xls/passes/optimization_pass.cc",
        "xls/passes/optimization_pass_registry.cc",
        "xls/passes/partial_info_query_engine.cc",
        "xls/passes/pass_base.cc",
        "xls/passes/query_engine.cc",
        "xls/passes/stateless_query_engine.cc",
        "xls/passes/union_query_engine.cc",
        "xls/solvers/solver.cc",
        "xls/solvers/z3_ir_translator.cc",
        "xls/solvers/z3_op_translator.cc",
        "xls/solvers/z3_utils.cc",
    ],
    hdrs = glob([
        "xls/**/*.h",
        "xls/**/*.inc",
        "xls/**/*.td",
        "xls/**/*.textproto",
        "xls/**/*.tpl",
    ], allow_empty = True),
    copts = [
        "-Wno-deprecated-declarations",
        "-Wno-deprecated-ofast",
        "-Wno-inconsistent-missing-override",
        "-Wno-nullability-completeness",
        "-Wno-unused-result",
        "-Wno-unused-value",
    ],
    includes = ["."],
    deps = [
        ":xls_c2rtl_cc_proto",
        "@abseil-cpp//absl/algorithm:container",
        "@abseil-cpp//absl/base",
        "@abseil-cpp//absl/base:core_headers",
        "@abseil-cpp//absl/base:nullability",
        "@abseil-cpp//absl/cleanup",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/container:fixed_array",
        "@abseil-cpp//absl/container:flat_hash_map",
        "@abseil-cpp//absl/container:flat_hash_set",
        "@abseil-cpp//absl/container:inlined_vector",
        "@abseil-cpp//absl/container:node_hash_map",
        "@abseil-cpp//absl/functional:function_ref",
        "@abseil-cpp//absl/hash",
        "@abseil-cpp//absl/log",
        "@abseil-cpp//absl/log:check",
        "@abseil-cpp//absl/log:vlog_is_on",
        "@abseil-cpp//absl/random:bit_gen_ref",
        "@abseil-cpp//absl/status",
        "@abseil-cpp//absl/status:statusor",
        "@abseil-cpp//absl/strings",
        "@abseil-cpp//absl/strings:str_format",
        "@abseil-cpp//absl/synchronization",
        "@abseil-cpp//absl/time",
        "@abseil-cpp//absl/types:compare",
        "@abseil-cpp//absl/types:span",
        "@boringssl//:crypto",
        "@cppitertools",
        "@googletest//:gtest",
        "@llvm-project//clang:ast",
        "@llvm-project//clang:basic",
        "@llvm-project//clang:frontend",
        "@llvm-project//clang:lex",
        "@llvm-project//clang:sema",
        "@llvm-project//clang:tooling",
        "@llvm-project//llvm:Support",
        "@or-tools//ortools/graph",
        "@protobuf",
        "@protobuf//:duration_cc_proto",
        "@protobuf//:protobuf_lite",
        "@protobuf//src/google/protobuf/io",
        "@protobuf//src/google/protobuf/io:tokenizer",
        "@re2",
        "@z3//:api",
    ],
)
