load("@xls_c2rtl_src//:dependency_support/z3/build_defs.bzl", "GEN_HDRS", "GEN_SRCS", "gen_srcs")
load("@rules_cc//cc:defs.bzl", "cc_library")

licenses(["notice"])

exports_files(["LICENSE"])

package(
    default_visibility = ["//visibility:private"],
    features = [
        "-layering_check",
        "-parse_headers",
    ],
)

gen_srcs()

common_copts = [
    "-fexceptions",
    "-fsigned-char",
    "-Wno-unused-variable",
    "-Wno-non-virtual-dtor",
    "-Wno-delete-non-virtual-dtor",
    "-Wno-switch",
    "-Wno-reorder",
    "-Wno-string-conversion",
    "-Wno-overloaded-virtual",
    "-D_MP_INTERNAL",
    "-D_AMD64_",
    "-D_USE_THREAD_LOCAL",
    "-D_EXTERNAL_RELEASE",
    "-D_LINUX_",
    "-D_NO_OMP_",
]

cc_library(
    name = "z3lib",
    srcs = GEN_SRCS + glob(
        [
            "src/ackermannization/*.cpp",
            "src/api/*.cpp",
            "src/ast/*.cpp",
            "src/ast/converters/*.cpp",
            "src/ast/euf/*.cpp",
            "src/ast/fpa/*.cpp",
            "src/ast/macros/*.cpp",
            "src/ast/normal_forms/*.cpp",
            "src/ast/pattern/*.cpp",
            "src/ast/proofs/*.cpp",
            "src/ast/rewriter/*.cpp",
            "src/ast/rewriter/bit_blaster/*.cpp",
            "src/ast/simplifiers/*.cpp",
            "src/ast/sls/*.cpp",
            "src/ast/substitution/*.cpp",
            "src/cmd_context/*.cpp",
            "src/cmd_context/extra_cmds/*.cpp",
            "src/math/automata/*.cpp",
            "src/math/dd/*.cpp",
            "src/math/euclid/*.cpp",
            "src/math/grobner/*.cpp",
            "src/math/hilbert/*.cpp",
            "src/math/interval/*.cpp",
            "src/math/lp/*.cpp",
            "src/math/polynomial/*.cpp",
            "src/math/realclosure/*.cpp",
            "src/math/simplex/*.cpp",
            "src/math/subpaving/*.cpp",
            "src/math/subpaving/tactic/*.cpp",
            "src/model/*.cpp",
            "src/muz/base/*.cpp",
            "src/muz/bmc/*.cpp",
            "src/muz/clp/*.cpp",
            "src/muz/dataflow/*.cpp",
            "src/muz/ddnf/*.cpp",
            "src/muz/fp/*.cpp",
            "src/muz/rel/*.cpp",
            "src/muz/spacer/*.cpp",
            "src/muz/tab/*.cpp",
            "src/muz/transforms/*.cpp",
            "src/nlsat/*.cpp",
            "src/nlsat/tactic/*.cpp",
            "src/opt/*.cpp",
            "src/params/*.cpp",
            "src/parsers/smt2/*.cpp",
            "src/parsers/util/*.cpp",
            "src/qe/*.cpp",
            "src/qe/lite/*.cpp",
            "src/qe/mbp/*.cpp",
            "src/sat/*.cpp",
            "src/sat/sat_solver/*.cpp",
            "src/sat/smt/*.cpp",
            "src/sat/tactic/*.cpp",
            "src/smt/*.cpp",
            "src/smt/params/*.cpp",
            "src/smt/proto_model/*.cpp",
            "src/smt/tactic/*.cpp",
            "src/solver/*.cpp",
            "src/solver/assertions/*.cpp",
            "src/tactic/*.cpp",
            "src/tactic/aig/*.cpp",
            "src/tactic/arith/*.cpp",
            "src/tactic/bv/*.cpp",
            "src/tactic/core/*.cpp",
            "src/tactic/fd_solver/*.cpp",
            "src/tactic/fpa/*.cpp",
            "src/tactic/portfolio/*.cpp",
            "src/tactic/sls/*.cpp",
            "src/tactic/smtlogics/*.cpp",
            "src/tactic/ufbv/*.cpp",
            "src/util/*.cpp",
            "src/util/lp/*.cpp",
        ],
        allow_empty = True,
        exclude = GEN_SRCS,
    ),
    hdrs = GEN_HDRS + glob(
        [
            "src/**/*.h",
            "src/**/*.hpp",
        ],
        allow_empty = True,
    ),
    copts = common_copts,
    include_prefix = "z3",
    includes = [
        "src/",
        "src/util",
    ],
)

cc_library(
    name = "api",
    hdrs = glob(
        [
            "src/api/z3*.h",
            "src/api/c++/z3++.h",
        ],
        allow_empty = True,
    ),
    include_prefix = "z3",
    includes = ["src/api"],
    visibility = ["//visibility:public"],
    deps = [":z3lib"],
)
