load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "scope_extraction",
    srcs = ["ScopeExtraction.cpp"],
    hdrs = ["ScopeExtraction.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//src/utils:kepler_formal_utils",
        "@naja",
        "@naja//:naja_extra_headers",
    ],
)
