load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "scope_extraction",
    srcs = ["ScopeExtraction.cpp"],
    hdrs = ["ScopeExtraction.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "@onetbb//:tbb",
        "//src/utils:kepler_formal_utils",
        "@naja//src/nl/netlist:naja_nl",
        "@naja//src/dnl:naja_dnl",
        "@naja//src/optimization:naja_opt",
    ],
)
