# tinyrocket_sec_config.yaml
format: verilog
verification: sec
sec_engine: k_induction
sec_encoding: dual_rail_steady
max_k: 32
input_paths:
  - tinyrocket.v
  - tinyrocket.v
liberty_files:
  - NangateOpenCellLibrary_typical.lib
  - fakeram45_1024x32.lib
  - fakeram45_64x32.lib
  - fakeram45_64x15.lib
log_level: info
solver: kissat
report_skipped_pos: true
