load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:tbb.bzl", "TBB_DEPS")

cc_library(
    name = "formal_structures",
    srcs = [
        "BoolExpr.cpp",
        "BoolExprCache.cpp",
        "BoolExprCnfWriter.cpp",
    ],
    hdrs = [
        "BoolExpr.h",
        "BoolExprCache.h",
        "BoolExprCnfWriter.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = TBB_DEPS,
)
