load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:naja_includes.bzl", "NAJA_HEADER_COPTS")
load("//bazel:tbb.bzl", "TBB_DEPS")

cc_library(
    name = "kepler_formal_utils",
    srcs = ["SNLLogicCone.cpp"],
    hdrs = ["SNLLogicCone.h"],
    copts = NAJA_HEADER_COPTS,
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = TBB_DEPS + [
        "//src/formal:formal_structures",
        "@naja",
        "@naja//:naja_extra_headers",
    ],
)
