load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "kepler_clocks",
    srcs = [
        "SecClockModel.cpp",
    ],
    hdrs = [
        "SecClockModel.h",
    ],
    includes = [
        "..",
        "../formal",
        "../sec",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/formal:formal_structures",
        "//src/sec:sec_common_headers",
        "//src/strategies:formal_strategies",
    ],
)
