# Copyright 2026 keplertech.io
# SPDX-License-Identifier: GPL-3.0-only

format: verilog
verification: lec
input_paths:
  - vexriscv_genfull_xilinx.v
  - vexriscv_genfull_xilinx_different.v
verilog_design1_top: vexriscv_genfull_xilinx_probe
verilog_design2_top: vexriscv_genfull_xilinx_probe
py_tech_files:
  - ../xilinx.py
log_level: info
solver: kissat
