load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel:naja_includes.bzl", "NAJA_HEADER_COPTS")

cc_test(
    name = "ScopeExtractionTests",
    srcs = ["ScopeExtractionTests.cpp"],
    copts = NAJA_HEADER_COPTS,
    deps = [
        "//src/clauses:kepler_clauses",
        "//src/formal:formal_structures",
        "//src/scope:scope_extraction",
        "//src/strategies:formal_strategies",
        "@naja",
        "@naja//:naja_extra_headers",
        "@googletest//:gtest_main",
    ],
)
