load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "kepler_clauses",
    srcs = [
        "SNLLogicCloud.cpp",
        "SNLTruthTableTree.cpp",
        "Tree2BoolExpr.cpp",
    ],
    hdrs = [
        "SNLLogicCloud.h",
        "SNLTruthTableTree.h",
        "Tree2BoolExpr.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = [
        "//src/formal:formal_structures",
        "@naja",
        "@naja//:naja_extra_headers",
    ],
)
