load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:naja_includes.bzl", "NAJA_HEADER_COPTS")
load("//bazel:tbb.bzl", "TBB_DEPS")

cc_library(
    name = "kepler_clauses",
    srcs = [
        "SNLLogicCloud.cpp",
        "SNLTruthTableTree.cpp",
        "Tree2BoolExpr.cpp",
    ],
    hdrs = [
        "SNLLogicCloud.h",
        "SNLTruthTableTree.h",
        "Tree2BoolExpr.h",
    ],
    copts = NAJA_HEADER_COPTS,
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = TBB_DEPS + [
        "//src/config:kepler_config",
        "//src/formal:formal_structures",
        "@naja",
        "@naja//:naja_extra_headers",
    ],
)
