# Copyright 2026 keplertech.io
# SPDX-License-Identifier: GPL-3.0-only

name: nix

on:
  pull_request:
  push:
    branches: [main, nixOS]
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-check:
    name: ${{ matrix.system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            system: x86_64-linux
          - os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          submodules: recursive
          persist-credentials: false
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
        with:
          install_url: https://releases.nixos.org/nix/nix-2.35.1/install
      - name: Check installed package
        run: nix flake check --system ${{ matrix.system }} --print-build-logs --no-update-lock-file
      - name: Build CLI package
        run: nix build .#packages.${{ matrix.system }}.default --print-build-logs --no-update-lock-file
