# GitHub Actions workflow to build kepler-formal and run LEC regressions.
name: regress-lec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: bash .github/scripts/install-cmake-deps-ubuntu.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_PREFIX_PATH="/usr/local;/usr/lib/llvm-14" -DENABLE_SANITIZERS=ON -DPYTHON_INTERFACE=OFF -DCMAKE_CXX_STANDARD=20

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      env:
        PYTHONMALLOC: malloc
      run: ctest -VV -E ".*[p|P]ython.*" -C ${{env.BUILD_TYPE}}

    - name: Clone kepler-formal-regress
      working-directory: ${{github.workspace}}
      run: git clone https://github.com/keplertech/kepler-formal-regress

    - name: Clone kepler-formal-examples
      working-directory: ${{github.workspace}}
      run: git clone https://github.com/keplertech/kepler-formal-examples

    - name: Run cts_aes_asap7_base
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          cts_aes_asap7_base \
          "${{github.workspace}}/kepler-formal-regress/cts_aes_asap7_base" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          objects/asap7/aes/base/4_rsz_lec_test.yml \
          expect-identical

    - name: Run sky130hd_gcd
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          sky130hd_gcd \
          "${{github.workspace}}/kepler-formal-regress/sky130hd_gcd" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          objects/sky130hd/gcd/base/4_rsz_lec_test.yml \
          expect-identical \
          po-cnfs

    - name: Run nangate45_black_parrot
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          nangate45_black_parrot \
          "${{github.workspace}}/kepler-formal-regress/nangate45_black_parrot" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          objects/nangate45/bp/base/4_rsz_lec_test.yml \
          expect-identical

    - name: Run ihp-sg13g2_i2c-gpio-expander
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          ihp_sg13g2_i2c_gpio_expander \
          "${{github.workspace}}/kepler-formal-regress/ihp-sg13g2_i2c-gpio-expander" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          objects/ihp-sg13g2/i2c-gpio-expander/base/4_rsz_lec_test.yml \
          expect-identical \
          po-cnfs

    - name: Run nangate45_swerv
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          nangate45_swerv \
          "${{github.workspace}}/kepler-formal-examples/nangate45_swerv" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          6_final_sec_test.yml \
          expect-identical

    - name: Run nangate45_ariane136
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          nangate45_ariane136 \
          "${{github.workspace}}/kepler-formal-examples/nangate45_ariane136" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          6_final_sec_test.yml \
          expect-identical

    - name: Run asap7_ethmac
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          asap7_ethmac \
          "${{github.workspace}}/kepler-formal-examples/asap7_ethmac" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          6_final_sec_test.yml \
          expect-identical

    - name: Run asap7_mock_alu
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          asap7_mock_alu \
          "${{github.workspace}}/kepler-formal-examples/asap7_mock-alu" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          6_final_sec_test.yml \
          expect-identical



    - name: Run on naja if
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          tinyrocket_naja_if \
          "${{github.workspace}}" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          regress/tinyrocket_naja_if/config.yaml

    - name: Run on verilog
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          tinyrocket_verilog \
          "${{github.workspace}}" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          regress/tinyrocket_verilog/config.yaml

    - name: Install najaeda
      run: pip install najaeda

    - name: Execute edit.py
      working-directory: ${{github.workspace}}/example
      run: python edit.py

    - name: Run on naja if edited
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          tinyrocket_naja_if_edited \
          "${{github.workspace}}" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          regress/tinyrocket_naja_if_edited/config.yaml

    - name: Run on verilog edited
      working-directory: ${{github.workspace}}
      run: |
        bash regress/run_cnf_regress.sh \
          tinyrocket_verilog_edited \
          "${{github.workspace}}" \
          "${{github.workspace}}/build/src/bin/kepler-formal" \
          regress/tinyrocket_verilog_edited/config.yaml
